[package]
name = "zuri_proto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.3.0"
glam = "0.22.0"
num = "0.4.0"
num-derive = "0.3.3"
num-traits = "0.2.15"
uuid = "1.2.2"
